name: supa_electronics
description: A Flutter app for Supa Electronics Store
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  web_socket_channel: ^3.0.1
  image_picker: ^1.1.2
  flutter_stripe: ^9.4.0
  

  url_launcher: ^6.3.0
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.3.1
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.1.5 
  uni_links: ^0.5.1


  path: ^1.8.3
  path_provider: ^2.1.2
  http_parser: ^4.0.2
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env 
    - assets/ezgif.com-video-to-gif-converter.gif
    - assets/image1.jpg
    - assets/image2.jpg
    - assets/image3.gif
    - assets/image4.mp4
    - assets/Image.png
    - assets/image5.jpg 
    - assets/image4.png 
    - assets/imm.png
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300